import { Job } from "./types";

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Software Engineer Intern",
    source_url: "https://greenhouse.io/shopify/swe-intern",
    company: { id: "c1", name: "Shopify", domain: "shopify.com" },
    location: "Ottawa, ON",
    location_type: "hybrid",
    job_type: "internship",
    term: "summer-2026",
    duration: "4 months",
    description: null,
    description_text:
      "Join Shopify's engineering team for a 4-month summer internship. You'll work on real production systems used by millions of merchants worldwide.\n\nResponsibilities:\n- Build and ship features end-to-end\n- Collaborate with senior engineers in code reviews\n- Write tests and documentation\n\nRequirements:\n- Currently enrolled in a CS or related program\n- Experience with Ruby, Go, or TypeScript\n- Comfortable with distributed systems concepts",
    posted_at: "2026-03-10T09:00:00Z",
    closing_at: "2026-03-18T23:59:00Z",
    deadline_type: "date",
    salary_min: 45,
    salary_max: 55,
    tags: ["TypeScript", "Go", "Ruby", "Distributed Systems"],
    status: "new",
    rank: null,
    notes: null,
    scraped_at: "2026-03-14T02:00:00Z",
    updated_at: "2026-03-14T02:00:00Z",
  },
  {
    id: "2",
    title: "Backend Engineering Intern",
    source_url: "https://jobs.lever.co/stripe/backend-intern",
    company: { id: "c2", name: "Stripe", domain: "stripe.com" },
    location: "Toronto, ON",
    location_type: "onsite",
    job_type: "internship",
    term: "summer-2026",
    duration: "4 months",
    description: null,
    description_text:
      "Stripe is looking for backend engineering interns to work on payments infrastructure.\n\nYou'll be embedded in a product team shipping features that process billions of dollars in transactions.\n\nWhat you'll do:\n- Design and implement APIs consumed by external developers\n- Improve reliability of Stripe's core payment flows\n- Participate in on-call rotations with mentorship\n\nWe use Ruby, Java, and Scala on the backend.",
    posted_at: "2026-03-08T14:00:00Z",
    closing_at: "2026-03-20T23:59:00Z",
    deadline_type: "date",
    salary_min: 55,
    salary_max: 65,
    tags: ["Ruby", "Java", "Scala", "APIs", "Payments"],
    status: "new",
    rank: null,
    notes: null,
    scraped_at: "2026-03-13T02:00:00Z",
    updated_at: "2026-03-13T02:00:00Z",
  },
  {
    id: "3",
    title: "Frontend Developer Co-op",
    source_url: "https://jobs.lever.co/notion/frontend-coop",
    company: { id: "c3", name: "Notion", domain: "notion.so" },
    location: "San Francisco, CA (Remote OK)",
    location_type: "remote",
    job_type: "internship",
    term: "fall-2026",
    duration: "8 months",
    description: null,
    description_text:
      "Notion is hiring a frontend co-op to help build the next generation of our editor.\n\nYou'll work closely with our design and product teams to ship user-facing features.\n\nStack: React, TypeScript, CSS-in-JS\n\nIdeal candidate:\n- Strong React fundamentals\n- Eye for design and UX details\n- Passionate about developer tools and productivity software",
    posted_at: "2026-03-12T10:00:00Z",
    closing_at: null,
    deadline_type: "rolling",
    salary_min: 40,
    salary_max: 50,
    tags: ["React", "TypeScript", "CSS", "Design Systems"],
    status: "new",
    rank: null,
    notes: null,
    scraped_at: "2026-03-14T02:00:00Z",
    updated_at: "2026-03-14T02:00:00Z",
  },
  {
    id: "4",
    title: "ML Platform Intern",
    source_url: "https://greenhouse.io/figma/ml-platform-intern",
    company: { id: "c4", name: "Figma", domain: "figma.com" },
    location: "New York, NY",
    location_type: "hybrid",
    job_type: "internship",
    term: "summer-2026",
    duration: "12 weeks",
    description: null,
    description_text:
      "Figma's ML Platform team is building infrastructure to power AI features across the product.\n\nAs an ML Platform Intern you will:\n- Build data pipelines for training and evaluation\n- Improve model serving latency and reliability\n- Collaborate with ML engineers to productionize research models\n\nTech: Python, PyTorch, Kubernetes, Spark",
    posted_at: "2026-03-05T08:00:00Z",
    closing_at: "2026-03-16T23:59:00Z",
    deadline_type: "date",
    salary_min: 50,
    salary_max: 60,
    tags: ["Python", "PyTorch", "Kubernetes", "ML", "Data Pipelines"],
    status: "new",
    rank: null,
    notes: null,
    scraped_at: "2026-03-12T02:00:00Z",
    updated_at: "2026-03-12T02:00:00Z",
  },
  {
    id: "5",
    title: "Software Developer Intern",
    source_url: "https://greenhouse.io/linear/swe-intern",
    company: { id: "c5", name: "Linear", domain: "linear.app" },
    location: "Remote",
    location_type: "remote",
    job_type: "internship",
    term: "summer-2026",
    duration: "4 months",
    description: null,
    description_text:
      "Linear is building the new standard for software project management. We're a small, high-output team that ships fast.\n\nThis is a full-stack internship — you'll work across our Electron app, web app, and Node.js backend.\n\nWe care deeply about performance, design, and developer experience. If you geek out over those things, you'll fit right in.\n\nStack: TypeScript, React, Node.js, PostgreSQL",
    posted_at: "2026-03-11T11:00:00Z",
    closing_at: null,
    deadline_type: "unknown",
    salary_min: null,
    salary_max: null,
    tags: ["TypeScript", "React", "Node.js", "PostgreSQL", "Electron"],
    status: "new",
    rank: null,
    notes: null,
    scraped_at: "2026-03-14T02:00:00Z",
    updated_at: "2026-03-14T02:00:00Z",
  },
  {
    id: "6",
    title: "Infrastructure Engineering Intern",
    source_url: "https://jobs.lever.co/vercel/infra-intern",
    company: { id: "c6", name: "Vercel", domain: "vercel.com" },
    location: "Remote",
    location_type: "remote",
    job_type: "internship",
    term: "winter-2027",
    duration: "4 months",
    description: null,
    description_text:
      "Join Vercel's infrastructure team and help scale the platform that powers millions of frontend deployments.\n\nYou'll work on:\n- Edge network and CDN optimizations\n- Build pipeline performance improvements\n- Internal developer tooling\n\nRequirements:\n- Familiarity with Linux, networking fundamentals\n- Experience with Go or Rust a plus\n- Interest in distributed systems and cloud infrastructure",
    posted_at: "2026-03-13T16:00:00Z",
    closing_at: "2026-04-15T23:59:00Z",
    deadline_type: "date",
    salary_min: 48,
    salary_max: 58,
    tags: ["Go", "Rust", "Networking", "CDN", "Linux"],
    status: "new",
    rank: null,
    notes: null,
    scraped_at: "2026-03-14T02:00:00Z",
    updated_at: "2026-03-14T02:00:00Z",
  },
];
